apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: devops-toolkit
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: devops-toolkit
  autoscalerRef:
    apiVersion: autoscaling/v1
    kind: HorizontalPodAutoscaler
    name: devops-toolkit
  progressDeadlineSeconds: 60
  service:
    port: 8080
    targetPort: 8080
    gateways:
    - public-gateway.istio-system.svc.cluster.local
    hosts:
    - devops-toolkit.34.139.90.59.nip.io
    trafficPolicy:
      tls:
        mode: DISABLE
  analysis:
    interval: 30s
    threshold: 2
    maxWeight: 60
    stepWeight: 20
    metrics:
    - name: request-success-rate
      thresholdRange:
        min: 99
      interval: 30s
    - name: request-duration
      thresholdRange:
        max: 500
      interval: 10s
