apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: devops-toolkit
  labels:
    app: devops-toolkit
spec:
  minReplicas: 2
  maxReplicas: 6
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: devops-toolkit
  targetCPUUtilizationPercentage: 80
