apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- ingress.yaml
- hpa.yaml
- canary.yaml
- ../../base
namespace: production
images:
- name: vfarcic/devops-toolkit-series
  newName: vfarcic/devops-toolkit-series
  newTag: 3.0.0
